# Generated by Django 4.0.4 on 2022-05-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('ano', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('professores', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=100)),
                ('ultimoNome', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=500)),
                ('outroLink', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('linkGit', models.CharField(max_length=500)),
                ('video', models.CharField(max_length=500)),
                ('ano', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
