# Generated by Django 4.0.4 on 2022-05-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='linkedin',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='outroLink',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linkGit',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='video',
            field=models.URLField(max_length=500),
        ),
    ]
