# Generated by Django 4.0.4 on 2022-05-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_elogio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaFormPW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta1', models.CharField(max_length=100)),
                ('pergunta2', models.CharField(max_length=100)),
                ('pergunta3', models.CharField(max_length=200)),
                ('pergunta4', models.CharField(max_length=800)),
                ('pergunta5', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
