# Generated by Django 4.0.4 on 2022-05-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_elogio_data_alter_respostaformpw_pergunta5'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaformpw',
            name='primeiroNome',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respostaformpw',
            name='ultimoNome',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
