# Generated by Django 4.0.4 on 2022-05-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_elogio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elogio',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
