# Generated by Django 4.0.4 on 2022-05-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_elogio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaformpw',
            name='pergunta3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='respostaformpw',
            name='pergunta4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='respostaformpw',
            name='pergunta5',
            field=models.CharField(max_length=100),
        ),
    ]
