# Generated by Django 4.0.4 on 2022-05-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_respostaformpw_pergunta3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='professor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='professores',
            field=models.CharField(max_length=500),
        ),
    ]
