# Generated by Django 4.0.4 on 2022-05-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_pessoa_professor_alter_cadeira_professores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='professores',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='professor',
            field=models.ManyToManyField(to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='professorAuxiliar',
            field=models.ManyToManyField(related_name='+', to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='semestre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='participante',
            field=models.ManyToManyField(to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='professor',
            field=models.ManyToManyField(related_name='+', to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='professorAuxiliar',
            field=models.ManyToManyField(related_name='+', to='portfolio.pessoa'),
        ),
    ]
