# Generated by Django 4.0.4 on 2022-05-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_cadeira_professores_cadeira_professor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cadeira',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='portfolio.pessoa'),
            preserve_default=False,
        ),
    ]
