# Generated by Django 4.0.4 on 2022-05-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_projeto_cadeira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='cadeira',
        ),
    ]
