# Generated by Django 4.0.4 on 2022-05-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_competencia_projeto_cadeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='cadeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='portfolio.cadeira'),
        ),
    ]
