# Generated by Django 4.0.4 on 2022-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_projeto_cadeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='aluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='professor',
            field=models.BooleanField(default=False),
        ),
    ]
