# Generated by Django 4.0.4 on 2022-05-27 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_pessoa_aluno_alter_pessoa_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='professorAuxiliar',
        ),
        migrations.AddField(
            model_name='projeto',
            name='competencia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.competencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologia',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='participante',
        ),
        migrations.AddField(
            model_name='projeto',
            name='participante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa'),
            preserve_default=False,
        ),
    ]
