# Generated by Django 4.0.4 on 2022-05-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_projeto_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='video',
        ),
    ]
