# Generated by Django 4.0.4 on 2022-05-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_remove_projeto_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=100)),
                ('ultimoNome', models.CharField(max_length=100)),
                ('pontuacao', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='RespostaFormPW',
        ),
    ]
