# Generated by Django 4.0.4 on 2022-05-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_pontuacaoquizz_delete_respostaformpw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontuacaoquizz',
            old_name='primeiroNome',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='pontuacaoquizz',
            name='ultimoNome',
        ),
    ]
