# Generated by Django 4.0.4 on 2022-05-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_rename_primeironome_pontuacaoquizz_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projeto',
            name='right',
            field=models.BooleanField(default=False),
        ),
    ]
