# Generated by Django 4.0.4 on 2022-05-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_remove_cadeira_professor_cadeira_professor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='linklusofona',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
