# Generated by Django 4.0.4 on 2022-05-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_cadeira_linklusofona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('corpo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
    ]
