# Generated by Django 4.0.4 on 2022-05-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='urlnoticia',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
