# Generated by Django 4.0.4 on 2022-05-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_noticia_urlnoticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
