# Generated by Django 4.0.4 on 2022-05-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_projeto_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='youtube',
        ),
    ]
