# Generated by Django 4.0.4 on 2022-05-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_remove_projeto_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
