# Generated by Django 4.0.4 on 2022-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_remove_projeto_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
